### ISSUE TITLE
Need a way to turn off the omnisearch box

### ISSUE THREAD

**Issue by blockimperiumdao** [FocalizeApp/focalize-extension#2]
While it is certainly useful, if you are constantly searching for developer docs, lens code and the like - the omnisearch bar gets in the way all the time. Just need a simple switch in the options to turn it off.

**Comment by iPaulPro** [comment]
I can certainly add an option for this, but I'm having a hard time understanding how exactly it's "in the way" since I am in the Lens docs and github all day and never have an issue.

Note that omnibox search is only active if you press tab after the word "lens". If you don't press tab, it's shouldn't be in the way at all.

**Comment by iPaulPro** [comment]
I'm on Brave and Mac and cannot reproduce this. What you're describing is not the normal behavior for the omnibox, it's an option you've enabled in brave://settings/searchEngines

![Screen Shot 2023-03-18 at 4 57 18 PM](https://user-images.githubusercontent.com/354227/226139560-27d52ab8-9a55-4439-866b-5b79b2743f05.jpg)

I can certainly see how that would be problematic and I don't see any situation where it's desirable. 😅

**Comment by iPaulPro** [comment]
Turns out that there actually is no way to disable to the omnibox keyword once it's specified in the manifest. Apologies, I suggest switching to "tab" only mode (as seen above), so this is not an issue.
